version: '3.8'

services:
  db:
    image: postgres:14
    container_name: chat_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: chatdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
