server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/chatdb
    username: user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true